config/routes.rb
Tasks::Application.routes.draw do

  devise_for :users

  resources :users, except: [:destroy, :new, :create, :edit, :update] do
    put :delete_status, on: :member
    get :system_tasks, on: :collection
    get :reasign_task, on: :collection
    resources :tasks, except: :destroy
  end

  root :to => 'users#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :status, :time_to_finish, :title, :created_at
  validates_presence_of :description, :status, :time_to_finish, :title, :user

  belongs_to :user

  STATUS = ['unstarted','started','finished']

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :phone, :role, :status, :photo
  validates_presence_of :email, :name, :phone, :role
  has_attached_file :photo, :styles => { :small => "50x50>"}

  has_many :tasks, :dependent => :delete_all

  scope :active, -> { where(status: 'active') }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	before_filter :get_user
  before_filter :authenticate_user!, except: [:index, :show]

	def get_user
		@user = User.find(params[:user_id])
	end

  def index
  	@tasks = @user.tasks
  end

  def new
    if current_user.id.equal?(@user.id)
      @task = Task.new
    else
      flash[:error] = "Not authorized to create new Task for this User"
      redirect_to users_path
    end
  end

  def edit
  	@task = @user.tasks.find(params[:id])

  end

  def update
  	@task = @user.tasks.find(params[:id])
  	@task.assign_attributes(params[:task])
    if @task.changed? & @task.save
      flash[:success] = "Task was successfully edited."
      redirect_to [@user, @task]
    else
      flash[:error] = "You must change at least one parameter"
      render 'edit'
    end
  end

  def create
    @task = Task.new(params[:task])
    @user.tasks << @task
    if @task.save
      @user.tasks << @task
      flash[:success] = "Task was successfully created."
      redirect_to [@user, @task]
    else
      render 'new'
    end
  end

  def show
  	@task = @user.tasks.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]

  def index
  	@users = User.active
  end

  def show
  	@user = User.find(params[:id])
  end

  def delete_status
    if current_user.id.equal?(params[:id])
      user = User.find(params[:id])
      user.status = "inactive"
      respond_to do |format|
        if user.save
          format.json { render json: {status: "saved"} }
        else
          format.json { render json: {status: "unsaved"} }
        end
      end
    else
      respond_to do |format|
        format.json { render json: {status: "not authorized"} }
      end
    end
  end

  def system_tasks
    @tasks = Task.all.sort_by { |x| [x.status == 'started' ? 1 : x.status == 'unstarted' ? 2 : 3, x.created_at]}
  end

  def reasign_task
    task = Task.find(params[:task_id])
    task.user_id = params[:task][:user]
    task.save
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper

	def render_error(*args)
		f = args[1]
		attribute = args[2]

		unless !args[0]
			errors_messages = args[0].errors.messages
			presence = errors_messages[attribute].present?
		else
			presence = false
		end

		html = ""
		if attribute.equal?(:current_password)
			html += "<div "+ (presence ? "style='color : #b94a48'" : "")+"> "+
			f.label(attribute, class: "inline") +	" <i class='info_password'>(we need your current password to confirm your changes)</i><br/> "+ f.password_field(attribute, style: (presence ? "border-color: #953b39;" : "")) +	" <span class='help-inline' "+ (presence ? "style='color : #b94a48'" : "") +">"+ (presence ? attribute.to_s.capitalize+" "+errors_messages[attribute][0] : "") +"</span> "+" </div>"
		else
			html +=
		  "<div class='control-group" + (presence ? " error'" : "'") +"> "+
		    f.label(attribute, :class => 'control-label') +
		    "<div class='controls'>"

	  	if attribute.equal?(:email)
				html += f.email_field(attribute, :class => 'text_field')
			elsif attribute.equal?(:password) | attribute.equal?(:password_confirmation) | attribute.equal?(:current_password)
				html += f.password_field(attribute, :class => 'text_field')
			else
				html += f.text_field(attribute, :class => 'text_field')
			end

	    html += "<span class='help-inline'>"+ (presence ? attribute.to_s.capitalize+" "+errors_messages[attribute][0] : "") +"</span>"+
		    "</div>
		  </div>"
		end
		raw(html)
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">

	<div class="navbar">
	  <div class="navbar-inner">
	  	<div id="user_nav">
		    <% if user_signed_in? %>
		      Logged in as <strong><%= current_user.email %></strong>.
		      <%= link_to 'Edit profile', edit_user_registration_path %> |
		      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
		    <% else %>
		      <%= link_to "Sign up", new_user_registration_path %> |
		      <%= link_to "Login", new_user_session_path %>
		    <% end %>
		  </div>
		  <%= yield :links%>
	  </div>
	</div>

	<% flash.each do |key, value| %>
	  <div class="alert alert-<%= key %>"><%= value %>
	  	<button type="button" class="close" data-dismiss="alert">&times;</button>
		</div>
  <% end %>
	<%= yield %>
</div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for [@user, @task], :html => { :class => 'form-horizontal' } do |f| %>

  <%= render_error(@task,f,:title) %>

  <%= render_error(@task,f,:description) %>

  <div class="control-group">
    <%= f.label :time_to_finish, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :time_to_finish, :class => 'date_select' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :status, Task::STATUS %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to "Back",
                :back, :class => 'btn' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<% content_for :links do %>
    <b class="brand" >Edit Task</b>
<% end %>
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<%- model_class = Task -%>
<% content_for :links do %>
    <b class="brand" >Tasks</b>
    <ul class="nav">
      <li><a href="<%= system_tasks_users_path%>">System Tasks</a></li>
      <li><a href="<%= users_path%>">System Users</a></li>
    </ul>
<% end %>

<table class="table table table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:time_to_finish) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.time_to_finish %></td>
        <td><%= task.status %></td>
        <td><%= task.user_id %></td>
        <td><%=l task.created_at %></td>
        <td>
          <%= link_to 'Show', [@user, task], :class => 'btn btn-mini'%>
          <%= if current_user.id.equal?(@user.id)
                link_to 'Edit', edit_user_task_path(@user, task), :class => 'btn btn-mini btn-info'
              end
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= if current_user.id.equal?(@user.id)
      link_to t('.new', :default => t("helpers.links.new")),
            new_user_task_path(@user),
            :class => 'btn btn-primary'
    end
%>
<%= link_to "Cancel",
                users_path, :class => 'btn' %>

app/views/tasks/new.html.erb
<% content_for :links do %>
    <b class="brand" >New Task</b>
<% end %>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%- model_class = Task -%>
<% content_for :links do %>
    <b class="brand" >Show Task</b>
<% end %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @task.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @task.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:time_to_finish) %>:</strong></dt>
  <dd><%= @task.time_to_finish %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @task.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @task.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to 'Users Tasks', user_tasks_path(@user), :class => 'btn'  %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>

  <%= render_error(@user,f,:name) %>

  <%= render_error(@user,f,:email) %>

  <%= render_error(@user,f,:phone) %>

  <%= render_error(@user,f,:role) %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <b class="brand" >Edit User</b>
  </div>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>

<% content_for :links do %>
  <b class="brand" >Users</b>
  <ul class="nav">
    <li><a href="<%= system_tasks_users_path%>">System Tasks</a></li>
  </ul>
<% end %>

<table class="table table table-hover">
  <thead>
    <tr>
      <th>Image</th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:role) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= image_tag user.photo.url(:small) %>
        </td>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.role %></td>
        <td><%= user.status %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to 'Show', user_path(user), :class => 'btn btn-small' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'delete_user btn btn-small btn-danger' %>

          <%= link_to 'Show Tasks', user_tasks_path(user), :class => 'btn btn-small show_tasks'%>
          <%= link_to 'New Task', new_user_task_path(user), :class => 'btn btn-small new_task' %>
          <%=
          if current_user and current_user.id.equal?(user.id)
                link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_registration_path, :class => 'btn btn-small btn-info'
              end
          %>
        </td>
        <input type="hidden" value="<%= user.id %>" class="user_id" />
      </tr>
    <% end %>
  </tbody>
</table>

<%#= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<% content_for :links do %>
	<b class="brand" >New User</b>
<% end %>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<% content_for :links do %>
  <b class="brand" >Show User</b>
<% end %>

<div class="container">
  <div class="row">
    <div class="span3">
      <%= image_tag @user.photo.url %>
    </div>
    <div class="span9">
      <dl class="dl-horizontal">
        <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
        <dd><%= @user.name %></dd>
        <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
        <dd><%= @user.email %></dd>
        <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
        <dd><%= @user.phone %></dd>
        <dt><strong><%= model_class.human_attribute_name(:role) %>:</strong></dt>
        <dd><%= @user.role %></dd>
        <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
        <dd><%= @user.status %></dd>
      </dl>
    </div>
  </div>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              :back, :class => 'btn'  %>
  <%= if current_user.id.equal?(@user.id)
        link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_registration_path, :class => 'btn btn-primary'
      end
  %>
</div>

app/views/users/sistem_tasks.html.erb
<%- model_class = Task -%>
<div class="navbar">
  <div class="navbar-inner">
    <b class="brand" >Sistem Tasks</b>
  </div>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:time_to_finish) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th>User assigned</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.time_to_finish %></td>
        <td><%= task.status %></td>
        <td><%= task.user_id %></td>
        <td><%=l task.created_at %></td>
        <td><%= select_tag "task[user]", options_from_collection_for_select(User.all, 'id', 'name', task.user_id), data: {
            remote: true,
            url: url_for( action: 'reasign_task', task_id: task.id)
          } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Back",
            users_path,
            :class => 'btn btn-primary' %>

app/views/users/system_tasks.html.erb
<%- model_class = Task -%>
<% content_for :links do %>
    <b class="brand" >Sistem Tasks</b>
<% end %>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:time_to_finish) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th>User assigned</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.time_to_finish %></td>
        <td><%= task.status %></td>
        <td><%= task.user_id %></td>
        <td><%=l task.created_at %></td>
        <td><%= select_tag "task[user]", options_from_collection_for_select(User.all, 'id', 'name', task.user_id), data: {
            remote: true,
            url: url_for( action: 'reasign_task', task_id: task.id)
          } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Back",
            users_path,
            :class => 'btn btn-primary' %>